# Implement The Linear Regression ML Models

In [1]:
import warnings
warnings.simplefilter(action='ignore')

In [2]:
# libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# import
df = pd.read_csv(r"Cleaned_data.csv")
df.head()

,area_type,location,total_sqft,bath,balcony,price,bhk
0,Super built-up Area,Electronic City Phase II,1056.0,2.0,1.0,39.07,2
1,Plot Area,Chikka Tirupathi,2600.0,5.0,3.0,120.00,4
2,Built-up Area,Uttarahalli,1440.0,2.0,3.0,62.00,3
3,Super built-up Area,Lingadheeranahalli,1521.0,3.0,1.0,95.00,3
4,Super built-up Area,Kothanur,1200.0,2.0,1.0,51.00,2

In [ ]:
## Model Building
# 1. select the numerical columns
# 2. seprate the x/features/input and y/label/target
# 2.1 split the data into training testing
# 3. load the algorithms and create the object of algoritms
# 4. train the model --> find the pattern value from data
# 5. test then model/predict
# 6. Evaluate/Performance matrix (accuracy)
# 7. fine tuning the model(for improve accuracy)

#### 1. with only numerical columns

In [4]:
# 1. select the numerical columns
df = df.drop(columns=["area_type","location"], axis=1)
df.head()

   total_sqft  bath  balcony   price  bhk
0      1056.0   2.0      1.0   39.07    2
1      2600.0   5.0      3.0  120.00    4
2      1440.0   2.0      3.0   62.00    3
3      1521.0   3.0      1.0   95.00    3
4      1200.0   2.0      1.0   51.00    2

In [5]:
# 2. seprate in the x and y
X = df.drop(columns=["price"])
y = df["price"]

In [6]:
X

       total_sqft  bath  balcony  bhk
0          1056.0   2.0      1.0    2
1          2600.0   5.0      3.0    4
2          1440.0   2.0      3.0    3
3          1521.0   3.0      1.0    3
4          1200.0   2.0      1.0    2
...           ...   ...      ...  ...
13315      3453.0   4.0      0.0    5
13316      3600.0   5.0      2.0    4
13317      1141.0   2.0      1.0    2
13318      4689.0   4.0      1.0    4
13319       550.0   1.0      1.0    1

[13320 rows x 4 columns]

In [7]:
y

0         39.07
1        120.00
2         62.00
3         95.00
4         51.00
          ...
13315    231.00
13316    400.00
13317     60.00
13318    488.00
13319     17.00
Name: price, Length: 13320, dtype: float64

#### 2. split the data into training testing

In [8]:
# 2. split the data into training testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X ,y,test_size = 0.2,random_state =34)

print(X_train.shape)
print(X_test.shape)

(10656, 4)
(2664, 4)

In [ ]:
print(y_train.shape)
print(y_test.shape)

In [ ]:
c = np.random.randint(1,10,20) # use for demonstrate the random state concept
# random state is used to get the same random number every time we run the code.
np.random.seed(42)
c

In [9]:
# 3. load the algorithms and create the object of algoritms y=Mx+c 
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [10]:
# 4. train the model --> find the pattern value from data
lr.fit(X_train,y_train)

LinearRegression()

In [11]:
# coffecient, intercept
print(lr.coef_)
print(lr.intercept_)

[ 0.06212005 30.16075516 -1.25283841 -2.31662009]
-56.362244004458105

In [12]:
# test -- > machine predictions for test data --> predicted y value
y_pred = lr.predict(X_test)
y_pred
# now we have the predicted value and actual value, we can evaluate the model performance

array([124.05657198, 214.0207618 ,  76.49176417, ..., 104.05391435,
        73.29013671, 128.35337879])

In [13]:
from sklearn.metrics import r2_score
# R2score for check variance
r2_score(y_test , y_pred)

0.3131376668306941

In [ ]:
# Improve the model 
#  1. add More data 
#  2. hyper parameter tuning 
#  3. change the Algorithms
#  4.

### 2. with categorical and numerical columns with pipeline Concept

In [ ]:
# 2nd way of preprocessing in ML

In [14]:
# import
from sklearn.linear_model import LinearRegression
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder,LabelEncoder ,StandardScaler
from sklearn.model_selection import train_test_split # train test split

In [15]:
df = pd.read_csv(r"Cleaned_data.csv")
df.head()

,area_type,location,total_sqft,bath,balcony,price,bhk
0,Super built-up Area,Electronic City Phase II,1056.0,2.0,1.0,39.07,2
1,Plot Area,Chikka Tirupathi,2600.0,5.0,3.0,120.00,4
2,Built-up Area,Uttarahalli,1440.0,2.0,3.0,62.00,3
3,Super built-up Area,Lingadheeranahalli,1521.0,3.0,1.0,95.00,3
4,Super built-up Area,Kothanur,1200.0,2.0,1.0,51.00,2

In [16]:
X = df.drop(columns=["price"])
y = df["price"]

# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# task 1 transform applying --> columns transform
columns_trans = ColumnTransformer(
    [('onehot_location', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), ['location']),
     ('onehot_area_type', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), ["area_type"]),
     ('scaler', StandardScaler(), ["total_sqft", "bath"]),
     ],
    remainder='passthrough')

# task 2 model a
lr = LinearRegression()

#pipeline
pipe = make_pipeline(columns_trans,lr)
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehot_location',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['location']),
                                                 ('onehot_area_type',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['area_type']),
                                                 ('scaler', StandardScaler(),
                                                  ['total_sqft', 'bath'])])),
                ('linearregression', LinearRegression())])

In [19]:
# Train the model --
pipe.fit(X_train , y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehot_location',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['location']),
                                                 ('onehot_area_type',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['area_type']),
                                                 ('scaler', StandardScaler(),
                                                  ['total_sqft', 'bath'])])),
                ('linearregression', LinearRegression())])

<bound method Pipeline.get_params of Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehot_location',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['location']),
                                                 ('onehot_area_type',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['area_type']),
                                                 ('scaler', StandardScaler(),
                                                  ['total_sqft', 'bath'])])),
                ('linearregression', LinearRegression())])>

In [20]:
# Predictions the answer from machine 
y_pred = pipe.predict(X_test)
y_pred

array([-21.38926386,  99.1724759 ,  88.68288232, ..., 107.54939043,
        54.24757811, 156.13436132])

In [21]:
pipe.score(X_test,y_test) # accuracy of the model

0.5867594610287413

# Performance Matrix
Measuring Performance metrics-Lost and Cost Function (MAE,MSE,RMSE,R2 Score)

In [22]:
# cost functions --> calculate erros
from sklearn.metrics import mean_absolute_error, mean_squared_error,root_mean_squared_error

print("MAE:",mean_absolute_error(y_test,y_pred))
print("MSE:",mean_squared_error(y_test,y_pred))
print("RMSE:",root_mean_squared_error(y_test,y_pred))

MAE: 39.88365353737957
MSE: 8798.113443139073
RMSE: 93.79825927563407

In [23]:
# Regression Performance check using r2_score ,and Adjusted r2 score
from sklearn.metrics import r2_score
r_squared = r2_score(y_test,y_pred)
r_squared
# https://benjaminobi.medium.com/what-really-is-r2-score-in-linear-regression-20cafdf5b87c

0.5867594610287413

In [26]:
df.shape

(13320, 7)

In [27]:
# adjusted_r2
n_samples = df.shape[0]
n_features = df.shape[1]
n_features

7

In [ ]:
n_samples

In [ ]:
adjusted_r2 = 1 - (1 - r_squared) * (n_samples - 1) / (n_samples - n_features - 1)
adjusted_r2
# https://www.shiksha.com/online-courses/articles/adjusted-r-squared/
# https://benjaminobi.medium.com/what-really-is-r2-score-in-linear-regression-20cafdf5b87c
# 0.586519790069246

In [31]:
# save the model for future use
import pickle
pickle.dump(pipe,open("model1.pkl","wb"))

In [32]:
# load the model
model = pickle.load(open("model.pkl","rb"))

In [34]:
df.sample(1)

,area_type,location,total_sqft,bath,balcony,price,bhk
10880,Super built-up Area,Thanisandra,1188.0,2.0,1.0,39.0,2

In [35]:
# # take input from user
location = input("Enter location: ")
area_type = input("Enter area type: ")
total_sqft = float(input("Enter total square feet: "))
bath = float(input("Enter number of bathrooms: "))
bhk = int(input("Enter number of bedrooms (BHK): "))
balcony = int(input("Enter number of balcony: "))

# # Create a DataFrame from user input
user_input = pd.DataFrame([[location, area_type, total_sqft, bath, bhk,balcony]],
                          columns=['location', 'area_type', 'total_sqft', 'bath', 'bhk',"balcony"])

user_input

      location            area_type  total_sqft  bath  bhk  balcony
0  Thanisandra  Super built-up Area      1188.0   2.0    1        2

In [ ]:
user_input

In [36]:
# # Predict the price
predicted_price = model.predict(user_input)
predicted_price

array([82.25674732])

In [37]:
print(f"The predicted price is: {predicted_price[0]:.2f} Lakhs")
# # Electronic City Phase II

The predicted price is: 82.26 Lakhs

In [ ]:
df

In [38]:
locations = df["location"].unique()
# save the data for future use
pickle.dump(locations, open("locations.pkl","wb"))

# carpet area
carpet_area = df["area_type"].unique()
# save the data for future use
pickle.dump(carpet_area, open("area_type.pkl","wb"))

In [ ]:
# gradio 
# streamlit
# flask/fastapi/django

In [ ]:
!pip install gradio pandas scikit-learn

In [ ]:
import gradio as gr
import pandas as pd
import pickle

# Load model
model = pickle.load(open("model.pkl", "rb"))

# Load dropdown values
locations = pickle.load(open("locations.pkl", "rb"))
area_types = pickle.load(open("area_type.pkl", "rb"))

# 🔑 FIX: convert to Python list
locations = list(locations)
area_types = list(area_types)

def predict_price(location, area_type, total_sqft, bath, bhk, balcony):

    user_input = pd.DataFrame(
        [[location, area_type, total_sqft, bath, bhk, balcony]],
        columns=['location', 'area_type', 'total_sqft', 'bath', 'bhk', 'balcony']
    )

    predicted_price = model.predict(user_input)[0]

    return f"🏠 Estimated House Price: ₹ {predicted_price:.2f} Lakhs"


interface = gr.Interface(
    fn=predict_price,
    inputs=[
        gr.Dropdown(choices=locations, label="Location"),
        gr.Dropdown(choices=area_types, label="Area Type"),
        gr.Number(label="Total Square Feet"),
        gr.Number(label="Bathrooms"),
        gr.Number(label="BHK"),
        gr.Number(label="Balcony"),
    ],
    outputs=gr.Textbox(label="Predicted Price"),
    title="🏡 House Price Prediction"
)

interface.launch()

:

### Save the Streamlit app code to app.py

In [ ]:
# with Dropdown meanu use
import streamlit as st
import pandas as pd
import pickle

# ----------------------
# Load Model & Dropdown Data
# ----------------------
pipe = pickle.load(open("model.pkl", "rb"))
locations = pickle.load(open("locations.pkl", "rb"))
area_types = pickle.load(open("area_type.pkl", "rb"))

# ----------------------
# Streamlit App
# ----------------------
st.set_page_config(page_title="House Price Prediction", layout="centered")
st.title("🏠 House Price Prediction App")
st.write("Enter property details below to get an estimated price (in Lakhs).")

# User inputs
location = st.selectbox("Select Location", locations)
area_type = st.selectbox("Select Area Type", area_types)
total_sqft = st.number_input("Enter Total Square Feet", min_value=100.0, step=10.0)
bath = st.number_input("Enter Number of Bathrooms", min_value=1.0, step=1.0)
bhk = st.number_input("Enter Number of Bedrooms (BHK)", min_value=1, step=1)
balcony = st.number_input("Enter number of Balcony: ", min_value=0)


# Prediction button
if st.button("Predict Price"):
    # Create DataFrame from inputs
    user_input = pd.DataFrame([[location, area_type, total_sqft, bath, bhk,balcony]],
                          columns=['location', 'area_type', 'total_sqft', 'bath', 'bhk','balcony'])

    # Make prediction
    predicted_price = pipe.predict(user_input)[0]

    st.success(f"💰 Estimated Price: **{predicted_price:.2f} Lakhs**")

In [ ]:
# steps
# 1. take all pkl files in one folder after training
# 2. create aap.py --> insert all code
# 3. create requirements.txt --> write all library which is needed to run project

In [ ]:
# For model improvement check relationship 
# and change models to improvement

In [ ]:
# Regression models --> 1. linear---> LinearRegression,OLS,SGDRegressor, ridge, lasso,eles(overfiting)
#       2. non-linear -->(Decision tree) DecisionTreeRegressor, SVR( support_vector_regression),KNNR
#               ensembles models --> RandomForestRegressor,GradientBoostingRegressor 

# classifications ---> Logistic regression(linear)
# (non-linear) SVM(SVC), KNN,naive bayes, Decision tree(classifier),RandomForestClassifer,
#       ensembles models --> all

# Deeplearning --> non-linear -Neural Network (only change in architecture for diffrent work)

### Topics
- Assumptions of Machine Learning(all ready done)
- Simple linear regression
- multiple linear regression
- variant of LR for RIDGE, LASSO ,ELASTICNET
- Measuring Performance metrics-Lost and Cost Function Model Evaluation Metrics ( MSE, MAE, RMSE)(R²-score, Adjusted R²-score)

variant of Linear models
- Polynomial Regression
- Linear Regression with OLS
- Linear Regression with SGD

- Under fitting and Overfitting
- Regularization ,Lasso & Ridge

# 1. assumption In Linear Regression

- Homoscedasticity

The variance of residuals should be approximately equal for all predicted values of the dependent variable.

- Normality - Errors are normally distributed

The residuals should be normally distributed.Linear relationship

There is a linear relationship between the dependent and independent variables

The error terms are normally distributed and the data do not contain outliers

- Independence of errors

The residual errors are independent of each other.

- No or low multicollinearity

There is no or little collinearity among input variables

#
https://www.geeksforgeeks.org/machine-learning/assumptions-of-linear-regression/
https://www.kdnuggets.com/2021/02/machine-learning-assumptions.html

![](https://media.geeksforgeeks.org/wp-content/uploads/20241025105428904464/Assumptions-of-Linear-Regression.webp)

<!-- #### MultiColiniarity
(optional)

- What it is

Multicollinearity occurs when independent variables are correlated, which can make it difficult to estimate each variable's relationship with the outcome variable.

- Why it's a problem

Multicollinearity can negatively impact model predictions on unseen data, and can make it difficult to explain the model's behavior.

- How to detect it

A correlation matrix can help identify multicollinearity, but a heatmap of correlations can be more intuitive. A variance inflation factor (VIF) can also be used to measure the amount of multicollinearity.

- How to address it

If multicollinearity is detected, it can be addressed by using a VIF to identify the correlated variables, and then removing or transforming those variables


from sklearn.datasets import fetch_california_housing
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = fetch_california_housing()
df = pd.DataFrame(data.data, columns = data.feature_names)
df['Price'] = data.target


#multicollinearity>> when one feature is explained by all other features
#when two features>> correlation
#more than two features>> vif, clustermap

sns.heatmap(df.corr(), annot = True, vmin = -1, vmax = 1)

#clustermap table shows group(cluster ) relationship
plt.figure(figsize = (5, 5))
sns.clustermap(df.corr(), vmin = -1, vmax =1, annot = True)

### What is the function of variance_inflation_factor?
Variance Inflation Factor (VIF)

A variance inflation factor (VIF) is a measure of the amount of multicollinearity in regression analysis. Multicollinearity exists when there is a correlation between multiple independent variables in a multiple regression model. This can adversely affect the regression results.


from statsmodels.stats.outliers_influence import variance_inflation_factor

vif = pd.DataFrame()
vif['Feature'] = df.columns
vif

vif["VIF"] = [variance_inflation_factor(df.values, i) for i in range(len(df.columns))]

df1 = df.copy()

df1.drop("Longitude", axis=1, inplace=True)
df1
vif = pd.DataFrame()
vif['Feature'] = df1.columns
vif["VIF"] = [variance_inflation_factor(df1.values, i) for i in range(len(df1.columns))]

vif

df1.drop("AveRooms", axis=1, inplace=True)
vif = pd.DataFrame()
vif['Feature'] = df1.columns
vif["VIF"] = [variance_inflation_factor(df1.values, i) for i in range(len(df1.columns))]

df1.drop("Latitude", axis=1, inplace=True)
vif = pd.DataFrame()
vif['Feature'] = df1.columns
vif["VIF"] = [variance_inflation_factor(df1.values, i) for i in range(len(df1.columns))]

Recursive Feature Elimination (RFE) is a feature selection method that iteratively removes features and trains a model on the remaining ones, evaluating its performance at each step. By repeatedly eliminating the least important features, RFE identifies the features that contribute most to the model's accuracy. It's a valuable tool for simplifying models and improving their efficiency.

#RFE >> recruseive feature elimination
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

from sklearn.feature_selection import RFE

rfe = RFE(estimator = LinearRegression(), n_features_to_select=6)

rfe.fit(X, y)

rfe.predict(X)

rfe.support_

X.columns

rfe.ranking_

 -->
rivision codes inside this markdown

## 2. Simple Linear Regression

- y=mx +c
single feature use

## 3. Multiple Linear Regression

- multiple  feature/X use
- y =M1x1 +M2x2 + M3x3 + MnXn +c