In [67]:
# Business Problem: To predict the price of a house based on various 
# features such as area type, location, size, etc.

# features data=  area type, location, size
# Label data = price -->check datatype(Continous data) --> Regression problem -->So use regession Algorithm

# regression Alogorithm:
# 1. Linear Alogorithm (Linear Regression)
# 2. Non Linear Regression (SVM, DT,RF, NB,KNN)

In [68]:
# 1. Linear Alogorithm (Linear Regression)

# Implement The Linear Regression ML Models

In [ ]:
import warnings
warnings.filterwarnings("ignore")

:

In [70]:
# importing the dataset
import pandas as pd
df = pd.read_csv(r"clean_data_EDA.csv")
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,price_per_sqft
0,Super built-up Area,19-Dec,Electronic City Phase II,2,Coomee,1056.0,2.0,1.0,39.07,3699.810606
1,Plot Area,Ready To Move,Chikka Tirupathi,4,Theanmp,2600.0,5.0,3.0,120.00,4615.384615
2,Built-up Area,Ready To Move,Uttarahalli,3,unknown,1440.0,2.0,3.0,62.00,4305.555556
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3,Soiewre,1521.0,3.0,1.0,95.00,6245.890861
4,Super built-up Area,Ready To Move,Kothanur,2,unknown,1200.0,2.0,1.0,51.00,4250.000000

In [71]:
## Model Building
# 1. select the numerical columns
# 2. seprate the x/features/input and y/label/target
# 2.1 split the data into training testing
# 3. load the algorithms and create the object of algoritms
# 4. train the model --> find the pattern value from data
# 5. test then model/predict
# 6. Evaluate/Performance matrix (accuracy)
# 7. fine tuning the model(for improve accuracy)

#### 1. with only numerical columns

In [72]:
# 1. select the numerical columns
df = df.drop(columns=["area_type","location","availability","society"], axis=1)
df.head()

   size  total_sqft  bath  balcony   price  price_per_sqft
0     2      1056.0   2.0      1.0   39.07     3699.810606
1     4      2600.0   5.0      3.0  120.00     4615.384615
2     3      1440.0   2.0      3.0   62.00     4305.555556
3     3      1521.0   3.0      1.0   95.00     6245.890861
4     2      1200.0   2.0      1.0   51.00     4250.000000

In [73]:
df.head()

   size  total_sqft  bath  balcony   price  price_per_sqft
0     2      1056.0   2.0      1.0   39.07     3699.810606
1     4      2600.0   5.0      3.0  120.00     4615.384615
2     3      1440.0   2.0      3.0   62.00     4305.555556
3     3      1521.0   3.0      1.0   95.00     6245.890861
4     2      1200.0   2.0      1.0   51.00     4250.000000

In [74]:
# 2. seprate in the x and y
X = df.drop(columns=["price"])
y = df["price"]

In [75]:
# remove the price_per_sqft which is not nessery for model building.
X = X.drop("price_per_sqft" ,axis=1)
X

       size  total_sqft  bath  balcony
0         2      1056.0   2.0      1.0
1         4      2600.0   5.0      3.0
2         3      1440.0   2.0      3.0
3         3      1521.0   3.0      1.0
4         2      1200.0   2.0      1.0
...     ...         ...   ...      ...
13314     5      3453.0   4.0      0.0
13315     4      3600.0   5.0      1.0
13316     2      1141.0   2.0      1.0
13317     4      4689.0   4.0      1.0
13318     1       550.0   1.0      1.0

[13319 rows x 4 columns]

In [76]:
y

0         39.07
1        120.00
2         62.00
3         95.00
4         51.00
          ...
13314    231.00
13315    400.00
13316     60.00
13317    488.00
13318     17.00
Name: price, Length: 13319, dtype: float64

#### 2. split the data into training testing

why do training testing split

Ans. for future use of data for predictions accuracy in unknown data

In [77]:
# 2. split the data into training testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X ,y,test_size = 0.2,random_state =4)

print(X_train.shape)
print(X_test.shape)

(10655, 4)
(2664, 4)

In [78]:
print(y_train.shape)
print(y_test.shape)

(10655,)
(2664,)

In [79]:
import numpy as np
c = np.random.randint(1,10,20) # use for demonstrate the random state concept
# random state is used to get the same random number every time we run the code.
np.random.seed(42)
c

array([5, 2, 5, 4, 8, 1, 5, 1, 4, 8, 1, 2, 1, 7, 2, 1, 6, 6, 2, 1],
      dtype=int32)

In [80]:
# 3. load the algorithms and create the object of algoritms y=Mx+c 
from sklearn.linear_model import LinearRegression
lr = LinearRegression() #object

In [81]:
# 4. train the model --> find the pattern value from data --> 
# find unknown value from data (y=mx + c) --> so find m,c 
lr.fit(X_train,y_train)

LinearRegression()

In [82]:
# coffecient, intercept
print(lr.coef_)
print(lr.intercept_)

[-8.12300214e+00  2.96281623e-04  5.69616280e+01  9.21284384e-01]
-20.004250270966708

In [83]:
# test -- > machine predictions for test data --> predicted y value
y_pred = lr.predict(X_test)
y_pred
# now we have the predicted value and actual value, we can evaluate the model performance

array([ 78.94034278, 129.09490015,  79.93629014, ...,  70.78978645,
       128.81284005, 178.85481041], shape=(2664,))

In [84]:
from sklearn.metrics import r2_score
# R2score for check variance
r2_score(y_test , y_pred)

0.1981933536928856

In [85]:
# Improve the model 
#  1. add More data 
#  2. hyper parameter tuning 
#  3. change the Algorithms
#  4. Experiment

### 2. with categorical and numerical columns with pipeline Concept

In [86]:
# 2nd way of preprocessing in ML

In [9]:
# import
from sklearn.linear_model import LinearRegression
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder,LabelEncoder ,StandardScaler
from sklearn.model_selection import train_test_split # train test split

In [11]:
df = pd.read_csv(r"clean_data_EDA.csv")
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,price_per_sqft
0,Super built-up Area,19-Dec,Electronic City Phase II,2,Coomee,1056.0,2.0,1.0,39.07,3699.810606
1,Plot Area,Ready To Move,Chikka Tirupathi,4,Theanmp,2600.0,5.0,3.0,120.00,4615.384615
2,Built-up Area,Ready To Move,Uttarahalli,3,unknown,1440.0,2.0,3.0,62.00,4305.555556
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3,Soiewre,1521.0,3.0,1.0,95.00,6245.890861
4,Super built-up Area,Ready To Move,Kothanur,2,unknown,1200.0,2.0,1.0,51.00,4250.000000

In [12]:
df.drop(columns=['availability','society','price_per_sqft'],axis=1,inplace=True)

In [13]:
df.head()

,area_type,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,Electronic City Phase II,2,1056.0,2.0,1.0,39.07
1,Plot Area,Chikka Tirupathi,4,2600.0,5.0,3.0,120.00
2,Built-up Area,Uttarahalli,3,1440.0,2.0,3.0,62.00
3,Super built-up Area,Lingadheeranahalli,3,1521.0,3.0,1.0,95.00
4,Super built-up Area,Kothanur,2,1200.0,2.0,1.0,51.00

In [14]:
X = df.drop(columns=["price"])
y = df["price"]

# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
# task 1 transform applying --> columns transform
columns_trans = ColumnTransformer(
    [('onehot_location', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), ['location']),
     ('onehot_area_type', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), ["area_type"]),
     ('scaler', StandardScaler(), ["total_sqft", "bath"]),
     ],
    remainder='passthrough')

# task 2 model a
lr = LinearRegression()

#pipeline
pipe = make_pipeline(columns_trans,lr)
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehot_location',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['location']),
                                                 ('onehot_area_type',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['area_type']),
                                                 ('scaler', StandardScaler(),
                                                  ['total_sqft', 'bath'])])),
                ('linearregression', LinearRegression())])

In [16]:
# Train the model --
pipe.fit(X_train , y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehot_location',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['location']),
                                                 ('onehot_area_type',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['area_type']),
                                                 ('scaler', StandardScaler(),
                                                  ['total_sqft', 'bath'])])),
                ('linearregression', LinearRegression())])

In [17]:
# Predictions the answer from machine 
y_pred = pipe.predict(X_test)
y_pred

array([899.74702494,  69.32273711,  51.64648499, ..., 134.07397359,
        50.35228701,  63.09056434], shape=(2664,))

In [18]:
pipe.score(X_test,y_test) # accuracy of the model

0.31902231608891574

# Performance Matrix
Measuring Performance metrics-Lost and Cost Function (MAE,MSE,RMSE,R2 Score)

In [19]:
# cost functions --> calculate erros
from sklearn.metrics import mean_absolute_error, mean_squared_error,root_mean_squared_error

print("MAE:",mean_absolute_error(y_test,y_pred))
print("MSE:",mean_squared_error(y_test,y_pred))
print("RMSE:",root_mean_squared_error(y_test,y_pred))

MAE: 51.1437821638439
MSE: 15881.835668429041
RMSE: 126.02315528675292

In [20]:
# Regression Performance check using r2_score ,and Adjusted r2 score
from sklearn.metrics import r2_score
r_squared = r2_score(y_test, y_pred)
r_squared
# https://benjaminobi.medium.com/what-really-is-r2-score-in-linear-regression-20cafdf5b87c

0.31902231608891574

In [21]:
df.shape

(13319, 7)

In [22]:
# adjusted_r2
n_samples = df.shape[0]
n_features = df.shape[1]
n_features

7

In [23]:
n_samples

13319

In [24]:
adjusted_r2 = 1 - (1 - r_squared) * (n_samples - 1) / (n_samples - n_features - 1)
adjusted_r2
# https://www.shiksha.com/online-courses/articles/adjusted-r-squared/
# https://benjaminobi.medium.com/what-really-is-r2-score-in-linear-regression-20cafdf5b87c
# 0.586519790069246

0.31866420296538056

In [25]:
# save the model for future use
import pickle
pickle.dump(pipe,open("model1.pkl","wb"))

In [26]:
import sklearn
sklearn.__version__

'1.8.0'

In [2]:
# load the model
import pickle
model = pickle.load(open("model1.pkl","rb"))

In [118]:
df.sample(1)

        area_type            location  size  total_sqft  bath  balcony  price
12907  Plot  Area  Horamavu Banaswadi     4       675.0   4.0      2.0   68.0

In [ ]:
# # take input from user
import pandas as pd
area_type = input("Enter area type: ")
location = input("Enter location: ")
size = int(input("Enter size: "))
total_sqft = float(input("Enter total square feet: "))
bath = float(input("Enter number of bathrooms: "))
balcony = int(input("Enter number of balcony: "))

# # Create a DataFrame from user input
user_input = pd.DataFrame([[area_type, location, size, total_sqft, bath, balcony]],
                          columns=['area_type', 'location', 'size', 'total_sqft', 'bath', "balcony"])

user_input

   area_type  location  size  total_sqft  bath  balcony
0  Plot Area  Horamavu     2         3.0   2.0        2

In [5]:
# # Predict the price
predicted_price = model.predict(user_input)
predicted_price

array([92.35426567])

In [6]:
print(f"The predicted price is: {predicted_price[0]:.2f} Lakhs")
# # Electronic City Phase II

The predicted price is: 92.35 Lakhs

In [ ]:
df

In [29]:
locations = df["location"].unique()
# save the data for future use
pickle.dump(locations, open("locations.pkl","wb"))

# carpet area
carpet_area = df["area_type"].unique()
# save the data for future use
pickle.dump(carpet_area, open("area_type.pkl","wb"))

In [112]:
# gradio 
# streamlit
# flask/fastapi/django

In [ ]:
%pip install gradio==4.44.0 huggingface_hub==0.23.0

In [ ]:
%pip install gradio

In [ ]:
import gradio as gr
import pandas as pd
import pickle

# Load model
model = pickle.load(open("model1.pkl", "rb"))

# Load dropdown values
locations = pickle.load(open("locations.pkl", "rb"))
area_types = pickle.load(open("area_type.pkl", "rb"))

# 🔑 FIX: convert to Python list
locations = list(locations)
area_types = list(area_types)

def predict_price(location, area_type, size, total_sqft, bath, bhk, balcony):

    user_input = pd.DataFrame(
        [[location, area_type, size, total_sqft, bath, bhk, balcony]],
        columns=['location', 'area_type', 'size', 'total_sqft', 'bath', 'bhk', 'balcony']
    )

    predicted_price = model.predict(user_input)[0]

    return f"🏠 Estimated House Price: ₹ {predicted_price:.2f} Lakhs"


interface = gr.Interface(
    fn=predict_price,
    inputs=[
        gr.Dropdown(choices=locations, label="Location"),
        gr.Dropdown(choices=area_types, label="Area Type"),
        gr.Number(label="Size"),
        gr.Number(label="Total Square Feet"),
        gr.Number(label="Bathrooms"),
        gr.Number(label="BHK"),
        gr.Number(label="Balcony"),
    ],
    outputs=gr.Textbox(label="Predicted Price"),
    title="🏡 House Price Prediction"
)

interface.launch(debug=True)

In [ ]:
# ModuleNotFoundError: No module named 'httpx'
%pip install httpx
# ModuleNotFoundError: No module named 'tqdm'
%pip install tqdm

### Save the Streamlit app code to app.py

In [ ]:
# =============================
# 🏠 House Price Prediction App (Streamlit)
# =============================

import streamlit as st
import pandas as pd
import pickle

# -----------------------------
# Page Config
# -----------------------------
st.set_page_config(
    page_title="House Price Predictor",
    page_icon="🏠",
    layout="wide"
)

# -----------------------------
# Load Model
# -----------------------------
model = pickle.load(open("model1.pkl", "rb"))

# -----------------------------
# Load Dropdown Values
# -----------------------------
locations = pickle.load(open("locations.pkl", "rb"))
area_types = pickle.load(open("area_type.pkl", "rb"))

# Convert to list
locations = list(locations)
area_types = list(area_types)

# -----------------------------
# UI Title
# -----------------------------
st.title("🏡 House Price Prediction App")
st.markdown("Enter property details to estimate price")

# -----------------------------
# Input Layout (2 Columns)
# -----------------------------
col1, col2 = st.columns(2)

with col1:
    location = st.selectbox("📍 Location", locations)
    area_type = st.selectbox("🏢 Area Type", area_types)
    size = st.number_input("📏 Size", min_value=1, step=1)

with col2:
    total_sqft = st.number_input("📐 Total Square Feet", min_value=100.0)
    bath = st.number_input("🛁 Bathrooms", min_value=1)
    bhk = st.number_input("🏠 BHK", min_value=1)
    balcony = st.number_input("🌇 Balcony", min_value=0)

# -----------------------------
# Prediction Button
# -----------------------------
if st.button("🔍 Predict Price"):

    try:
        # Create DataFrame
        user_input = pd.DataFrame(
            [[location, area_type, size, total_sqft, bath, bhk, balcony]],
            columns=['location', 'area_type', 'size', 'total_sqft', 'bath', 'bhk', 'balcony']
        )

        # Prediction
        predicted_price = model.predict(user_input)[0]

        # Output
        st.success(f"🏠 Estimated House Price: ₹ {predicted_price:.2f} Lakhs")

    except Exception as e:
        st.error(f"❌ Error: {str(e)}")

# -----------------------------
# Footer
# -----------------------------
st.markdown("---")
st.caption("Built with ❤️ using Streamlit")

In [ ]:
# steps
# 1. take all pkl files in one folder after training
# 2. create aap.py --> insert all code
# 3. create requirements.txt --> write all library which is needed to run project

In [ ]:
# For model improvement check relationship 
# and change models to improvement

In [ ]:
# Regression models --> 1. linear---> LinearRegression,OLS,SGDRegressor, ridge, lasso,eles(overfiting)
#       2. non-linear -->(Decision tree) DecisionTreeRegressor, SVR( support_vector_regression),KNNR
#               ensembles models --> RandomForestRegressor,GradientBoostingRegressor 

# classifications ---> Logistic regression(linear)
# (non-linear) SVM(SVC), KNN,naive bayes, Decision tree(classifier),RandomForestClassifer,
#       ensembles models --> all

# Deeplearning --> non-linear -Neural Network (only change in architecture for diffrent work)

### Topics
- Assumptions of Machine Learning(all ready done)
- Simple linear regression
- multiple linear regression
- variant of LR for RIDGE, LASSO ,ELASTICNET
- Measuring Performance metrics-Lost and Cost Function Model Evaluation Metrics ( MSE, MAE, RMSE)(R²-score, Adjusted R²-score)

variant of Linear models
- Polynomial Regression
- Linear Regression with OLS
- Linear Regression with SGD

- Under fitting and Overfitting
- Regularization ,Lasso & Ridge

# 1. assumption In Linear Regression

- Homoscedasticity

The variance of residuals should be approximately equal for all predicted values of the dependent variable.

- Normality - Errors are normally distributed

The residuals should be normally distributed.Linear relationship

There is a linear relationship between the dependent and independent variables

The error terms are normally distributed and the data do not contain outliers

- Independence of errors

The residual errors are independent of each other.

- No or low multicollinearity

There is no or little collinearity among input variables

#
https://www.geeksforgeeks.org/machine-learning/assumptions-of-linear-regression/
https://www.kdnuggets.com/2021/02/machine-learning-assumptions.html

![](https://media.geeksforgeeks.org/wp-content/uploads/20241025105428904464/Assumptions-of-Linear-Regression.webp)

<!-- #### MultiColiniarity
(optional)

- What it is

Multicollinearity occurs when independent variables are correlated, which can make it difficult to estimate each variable's relationship with the outcome variable.

- Why it's a problem

Multicollinearity can negatively impact model predictions on unseen data, and can make it difficult to explain the model's behavior.

- How to detect it

A correlation matrix can help identify multicollinearity, but a heatmap of correlations can be more intuitive. A variance inflation factor (VIF) can also be used to measure the amount of multicollinearity.

- How to address it

If multicollinearity is detected, it can be addressed by using a VIF to identify the correlated variables, and then removing or transforming those variables


from sklearn.datasets import fetch_california_housing
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = fetch_california_housing()
df = pd.DataFrame(data.data, columns = data.feature_names)
df['Price'] = data.target


#multicollinearity>> when one feature is explained by all other features
#when two features>> correlation
#more than two features>> vif, clustermap

sns.heatmap(df.corr(), annot = True, vmin = -1, vmax = 1)

#clustermap table shows group(cluster ) relationship
plt.figure(figsize = (5, 5))
sns.clustermap(df.corr(), vmin = -1, vmax =1, annot = True)

### What is the function of variance_inflation_factor?
Variance Inflation Factor (VIF)

A variance inflation factor (VIF) is a measure of the amount of multicollinearity in regression analysis. Multicollinearity exists when there is a correlation between multiple independent variables in a multiple regression model. This can adversely affect the regression results.


from statsmodels.stats.outliers_influence import variance_inflation_factor

vif = pd.DataFrame()
vif['Feature'] = df.columns
vif

vif["VIF"] = [variance_inflation_factor(df.values, i) for i in range(len(df.columns))]

df1 = df.copy()

df1.drop("Longitude", axis=1, inplace=True)
df1
vif = pd.DataFrame()
vif['Feature'] = df1.columns
vif["VIF"] = [variance_inflation_factor(df1.values, i) for i in range(len(df1.columns))]

vif

df1.drop("AveRooms", axis=1, inplace=True)
vif = pd.DataFrame()
vif['Feature'] = df1.columns
vif["VIF"] = [variance_inflation_factor(df1.values, i) for i in range(len(df1.columns))]

df1.drop("Latitude", axis=1, inplace=True)
vif = pd.DataFrame()
vif['Feature'] = df1.columns
vif["VIF"] = [variance_inflation_factor(df1.values, i) for i in range(len(df1.columns))]

Recursive Feature Elimination (RFE) is a feature selection method that iteratively removes features and trains a model on the remaining ones, evaluating its performance at each step. By repeatedly eliminating the least important features, RFE identifies the features that contribute most to the model's accuracy. It's a valuable tool for simplifying models and improving their efficiency.

#RFE >> recruseive feature elimination
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

from sklearn.feature_selection import RFE

rfe = RFE(estimator = LinearRegression(), n_features_to_select=6)

rfe.fit(X, y)

rfe.predict(X)

rfe.support_

X.columns

rfe.ranking_

 -->
rivision codes inside this markdown

## 2. Simple Linear Regression

- y=mx +c
single feature use

## 3. Multiple Linear Regression

- multiple  feature/X use
- y =M1x1 +M2x2 + M3x3 + MnXn +c